--create database DBCRUDN
--USE DBCRUDN

CREATE TABLE DEPARTAMENT(
ID_DEPARTAMENTO INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(50)
)

CREATE TABLE EMPLEADO(
ID_EMPLEADO INT PRIMARY KEY IDENTITY,
NOMBRE_COMPLETO VARCHAR(50),
ID_DEPARTAMENTO INT REFERENCES DEPARTAMENT(ID_DEPARTAMENTO),
SUELDO DECIMAL(10,2),
FECHA_CONTRATO DATE
)

INSERT INTO DEPARTAMENT(NOMBRE) VALUES('ADMINISTRACION'),('PROGRAMACION'),('TICS'),('MARKETING')

SELECT * FROM DEPARTAMENT

INSERT INTO EMPLEADO(NOMBRE_COMPLETO,ID_DEPARTAMENTO,SUELDO,FECHA_CONTRATO) VALUES ('EDGAR VILLAVICENCIO',2,500,GETDATE())

SELECT * FROM EMPLEADO


--Funcion para obtener la lista de departamentos

CREATE FUNCTION FN_DEPARTAMENTOS()
RETURNS TABLE
AS
RETURN
SELECT ID_DEPARTAMENTO, NOMBRE FROM DEPARTAMENT


-- FUNCION PARA OBTENER LA LISTA DE EMPLEADOS

CREATE FUNCTION FN_EMPLEADOS()
RETURNS TABLE
AS
RETURN
SELECT EMPLEADO.ID_EMPLEADO, EMPLEADO.NOMBRE_COMPLETO,DEPARTAMENT.ID_DEPARTAMENTO, DEPARTAMENT.NOMBRE,
EMPLEADO.SUELDO,CONVERT(char(10),EMPLEADO.FECHA_CONTRATO,103)[FECHA_CONTRATO] 
FROM EMPLEADO INNER JOIN DEPARTAMENT ON EMPLEADO.ID_DEPARTAMENTO = DEPARTAMENT.ID_DEPARTAMENTO 

--FUNCION PARA QUE NOS DEVUELVA UNICAMENTE LA INFORMACION DE UN EMPLEADO

CREATE FUNCTION FN_EMPLEADO(@ID_EMPLEADO INT)
RETURNS TABLE
AS
RETURN
SELECT EMPLEADO.ID_EMPLEADO, EMPLEADO.NOMBRE_COMPLETO,DEPARTAMENT.ID_DEPARTAMENTO, DEPARTAMENT.NOMBRE,
EMPLEADO.SUELDO,CONVERT(char(10),EMPLEADO.FECHA_CONTRATO,103)[FECHA_CONTRATO] 
FROM EMPLEADO INNER JOIN DEPARTAMENT ON EMPLEADO.ID_DEPARTAMENTO = DEPARTAMENT.ID_DEPARTAMENTO  WHERE EMPLEADO.ID_EMPLEADO = @ID_EMPLEADO


--PROCEDIMIENTOS ALMACENADOS  CREAR EMPLEADO
CREATE PROC SP_CREAR_EMPLEADO(
@NOMBRE_COMPLETO VARCHAR(50),
@ID_DEPARTAMENTO INT,
@SUELDO DECIMAL(10,2),
@FECHA_CONTRATO VARCHAR(10)
) AS
BEGIN
 SET DATEFORMAT DMY
 INSERT INTO EMPLEADO(NOMBRE_COMPLETO,ID_DEPARTAMENTO,SUELDO,FECHA_CONTRATO) VALUES (@NOMBRE_COMPLETO,@ID_DEPARTAMENTO,@SUELDO,CONVERT(DATE,@FECHA_CONTRATO))
END


--PROCEDIMIENTOS ALMACENADOS EDITAR EMPLEADO

CREATE PROC SP_EDITAR_EMPLEADO(
@ID_EMPLEADO INT,
@NOMBRE_COMPLETO VARCHAR(50),
@ID_DEPARTAMENTO INT,
@SUELDO DECIMAL(10,2),
@FECHA_CONTRATO VARCHAR(10)
) AS
BEGIN
 SET DATEFORMAT DMY
 UPDATE EMPLEADO SET NOMBRE_COMPLETO = @NOMBRE_COMPLETO,
					 ID_DEPARTAMENTO = ID_DEPARTAMENTO,
					 SUELDO = @SUELDO,
					 FECHA_CONTRATO = CONVERT(DATE,@FECHA_CONTRATO) WHERE ID_EMPLEADO = @ID_EMPLEADO
END


--PROCEDIMIENTOS ALMACENADOS ELIMINAR EMPLEADO

CREATE PROC SP_ELIMINAR_EMPLEADO(
@ID_EMPLEADO INT
) AS
BEGIN
	DELETE FROM EMPLEADO WHERE ID_EMPLEADO = @ID_EMPLEADO
END


